/**This is an autogenerated file. DO NOT EDIT.**/
const input_file = [
  {
    "x": 0,
    "y": 0,
    "w": 500,
    "h": 600,
    "baseHue": 255,
    "colorSaturation": 0,
    "colorLightness": 100,
    "drawGrid": true,
    "gridColor": 23
  }
];