const { watch } = require("fs")
const fs = require('fs');
const dotenv = require('dotenv');

dotenv.config();

function loadExampleInClient() {
  const file = fs.readFileSync(`./examples/${process.env.EXAMPLE_FILE}.json`, { encoding: 'utf-8' });
  const js = `/**This is an autogenerated file. DO NOT EDIT.**/\nconst input_file = ${file};`

  fs.writeFileSync('./client/src/input_file.js', js);
}

exports.default = function() {
  loadExampleInClient();
  watch('examples', loadExampleInClient);
}


